# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

#######   友盟基础库     #######
pod 'UMCCommon'
pod 'UMCSecurityPlugins' #pod ‘UMCSecurityPlugins’为安全组件，不需要开发者显式调用，为开发者提供安全的数据环境，能有效的防止刷量和反作弊等行为，属于可选项，如果对App的数据安全性要求不高的话，可以去掉此pod。


pod 'UMCCommonLog' #开发阶段进行调试SDK及相关功能使用，可在发布 App 前移除


#######   下面是分享的平台，用到哪个平台导入哪个平台，避免项目包过大    ######
# 集成微信(精简版0.2M)
pod 'UMCShare/Social/ReducedWeChat'
# 集成QQ/QZone/TIM(精简版0.5M)
pod 'UMCShare/Social/ReducedQQ'
# 集成新浪微博(精简版1M)
pod 'UMCShare/Social/ReducedSina'

######    友盟统计       #######
pod 'UMCAnalytics'#统计 SDK



#######    友盟推送        #######
pod 'UMCPush' #Push SDK






target 'CommonToolDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CommonToolDemo

end
